### ISSUE TITLE
Search history stopped working after update

### ISSUE THREAD

**Issue by leram84** [theotherp/nzbhydra#539]
Not sure if it was the latest release, but one of the last few broke it for me. 

![screenshot 2017-02-06 at 10 55 28 pm](https://cloud.githubusercontent.com/assets/21117493/22677279/66feab00-ecbf-11e6-911b-878068cc49c7.png)

**Comment by albino1** [comment]
I have the same problem, FWIW.  Just get that partial black box when I click the drop down.

**Comment by theotherp** [comment]
Ah, it's the "search search history". Hm yes, I'll check it out.

**Comment by theotherp** [comment]
Works fine for me. What does the "regular" search history show?

**Comment by leram84** [comment]
nope, still same problem. I saw your last message, and yes, the main search history section does work as expected, but the search search history is still just a little black box with nothing in it.

**Comment by theotherp** [comment]
Please send your debugging infos.

**Comment by leram84** [comment]
ok, what should i set the log settings too? (log level, console log level, etc)

**Comment by theotherp** [comment]
Doesn't matter, I want to see the configuration. I hope there is something
in there that differs from mine and explains it.

**Comment by leram84** [comment]
ok, sorry for the noobness, but what exactly are you looking for? There is a nzbhydra.log file (as well as nzbhydra.log.1 and nzbhydra.log.3), but it has a lot of sensitive info in it... I guess i could go through and edit it, but its long. If i delete it, will a new one be created automatically that would be shorter and easier to edit. Just wanted to make sure thats what you're even after before i start.

**Comment by theotherp** [comment]
You know, when you created this issue the page looked like this:

![firefox_2017-02-09_08-36-07](https://cloud.githubusercontent.com/assets/14368889/22773516/e3e2a20e-eea2-11e6-9225-be7d7f528908.png)

You ignored that, deleted it and wrote your text. I think I will ignore and close every issue that doesn't follow the template because FFS this would be so much easier if people followed it.

So, in the system section there's a tab for bug reports. It should (hopefully) create ZIP which contains an anonymized log and settings.cfg.

**Comment by theotherp** [comment]
Should hopefully, actually be fixed in next version.

**Comment by theotherp** [comment]
Please comment if this is not yet fixed.

**Comment by jaywk** [comment]
This bug is still present for me. The "search search history" is blank.

**Comment by theotherp** [comment]
I'll take a look. Do you use multiple users?

**Comment by jaywk** [comment]
No.

**Comment by theotherp** [comment]
What does http://127.0.0.1:5075/internalapi/getsearchrequestsforsearching return?

**Comment by jaywk** [comment]
```
{
  "searchRequests": [
    {
      "author": null,
      "category": "TV",
      "episode": "13",
      "identifier_key": "tvdbid",
      "identifier_value": "276526",
      "internal": true,
      "movietitle": null,
      "query": "",
      "season": "3",
      "time": "Fri, 14 Apr 2017 19:26:40 GMT",
      "title": "The Legend of Mick Dodge",
      "tvtitle": "The Legend of Mick Dodge",
      "type": "tv",
      "username": "nzbhydra"
    }
  ],
  "totalRequests": 1
```

It would have been more accurate for me to say there is only one result showing up and hydra has stopped updating with recent searches but jumped onto this issue instead of creating a new one since it was in the vein. I can create a new issue if you'd like. Anyway the result is above. I checked my actual search history for this and it was searched on 2017-04-14 08:27 and I have conducted lots of searches since then. I tend to update within 24 hours of new releases being announced if that helps narrow down anything on your end. Let me know if I need to provide anything else.

**Comment by theotherp** [comment]
... Yes that would've been more accurate because the original problem was with the box being empty. ffs.
